name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 89.104.71.29
        username: root
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /opt/gradio-app
          ./deploy.sh
